version: '3.9'
services:
#  configuraciones de la base de datos
  database:
    image: mysql:8.0
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
    volumes:
        - db_data:/var/lib/mysql
    networks:
        - wpsite



# configuraciones de los servicios de wordpress

# confifuraciones de los servicios de phpmyadmin: