version: '3.9'
services:
#  configuraciones de la base de datos
  database:
    image: mysql:8.0
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
        - db_data:/var/lib/mysql
    networks:
        - wpsite
# configuraciones de los servicios de wordpress
  wordpress:
    image:
        wordpress:latest
    depends_on:
      - database
    ports:
      - "8000:80"
    restart: always
    environment:
        WORDPRESS_DB_HOST: database:3306
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: root
    volumes:
      - .:/var/www/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wpsite

# configuraciones de los servicios de phpmyadmin:
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
        - "8080:80"
    environment:
        PMA_HOST: database
        MYSQL_ROOT_PASSWORD: pass
    networks:
        - wpsite

networks:
    wpsite:

volumes:
    db_data:



